
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/qq820069931/sprincloud-config.git
          search-paths:
            - springcloud-config
      label: master

user:
  age: 18

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
